version: 2
updates:
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 21
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    cooldown:
      default-days: 21
    directory: "/elasticsearch/"
    schedule:
      interval: "daily"
