version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - kernelsam
    cooldown:
      default-days: 21
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    assignees:
      - barrycaceres
    cooldown:
      default-days: 21
    directory: "/elasticsearch/"
    schedule:
      interval: "daily"
